#!/bin/bash

set -e

echo yes | vendor/bin/drush si boulder_profile \
  --db-url="mysql://db:db@db:3306/db" \
  --site-name="Web Express D11 Test Site" \
  --account-name="admin" \
  --account-pass="sandpoint.test" \
  install_configure_form.enable_update_status_module=NULL \
  install_configure_form.enable_update_status_emails=NULL

# vendor/bin/drush pmu simplesamlphp_auth -y

echo -e "\nLogin with Username: admin\nPassword: sandpoint.test"
echo -e "Site URL: ${DDEV_PRIMARY_URL}\n"

